import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-red-500"
      >
        <AuthProvider>
          <Theme>
            <NavBar />
            <main className="p-2">
              {children}
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
